spring:
  application:
    name: commerce-system

  datasource:
    url: jdbc:postgresql://localhost:5432/commerce_db?currentSchema=commerce
    username: postgres
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
